name: markdown-link-check
on:
  pull_request:
    paths: [ "articles/**.md", "books/**.md" ]
  workflow_dispatch:
jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          config-file: ".github/mlc-config.json"
