name: security-scan
on:
  pull_request:
    paths: [ "articles/**", "books/**", "images/**", ".github/**" ]
  push:
    branches: [ main ]
    paths: [ "articles/**", "books/**", "images/**", ".github/**" ]
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-banner --redact
